image:
  repository: bitnami/postgres-exporter
  tag: 0.9.0
  pullPolicy: IfNotPresent

auto_discover_databases: true
rds: false
pg_stat_statements: true
pg_stat_user_tables: true
light_threshold: 0
pg_client_connections: true
version: "12"
username: postgres
password: pgpass
master: master:5432/postgres?sslmode=require
replicas:
  - replica0:5432/postgres?sslmode=require
  - replica1:5432/postgres?sslmode=require
  - replica2:5432/postgres?sslmode=require
additionalLabels:
  site: pg-12-prod
  line: prod
